-- AlterTable
ALTER TABLE "PlayerState" ADD COLUMN "vehicleTaxi" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PlayerState" ADD COLUMN "vehicleForklift" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PlayerState" ADD COLUMN "vehicleArmoredTruck" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PlayerState" ADD COLUMN "vehicleDeliveryTruck" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PlayerState" ADD COLUMN "vehicleBus" INTEGER NOT NULL DEFAULT 0;
