-- AlterTable
ALTER TABLE "PlayerState" ADD COLUMN "coinBoostPercent" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PlayerState" ADD COLUMN "xpBoostPercent" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PlayerState" ADD COLUMN "coinBoostExpiresAt" BIGINT NOT NULL DEFAULT 0;
ALTER TABLE "PlayerState" ADD COLUMN "xpBoostExpiresAt" BIGINT NOT NULL DEFAULT 0;
