-- AlterTable
ALTER TABLE "PlayerState" ADD COLUMN "tokenGreen" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PlayerState" ADD COLUMN "tokenBlue" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PlayerState" ADD COLUMN "tokenYellow" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PlayerState" ADD COLUMN "tokenPurple" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PlayerState" ADD COLUMN "tokenRed" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PlayerState" ADD COLUMN "dailyTasksProgress" JSONB NOT NULL DEFAULT '{}';
ALTER TABLE "PlayerState" ADD COLUMN "dailyTasksClaimed" JSONB NOT NULL DEFAULT '[]';
ALTER TABLE "PlayerState" ADD COLUMN "dailyTasksDoubleReward" BOOLEAN NOT NULL DEFAULT false;
